name: funkoff
description: An over-powered engine to evaluate mathematical graph functions.
version: 1.4.0
homepage: https://github.com/iamtheblackunicorn/FunkOff
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  pedantic: ^1.11.0
